### ISSUE TITLE
The meanning for the N, M, T, V, C = x.size()

### ISSUE THREAD

**Issue by CristinaZN** [firework8/ProtoGCN#1]
Hi,

Could you explain what is the meaning of N, M, T, V, C in the file /ProtoGCN/protogcn/models/gcns/protogcn.py line 154?

Regards
Cristinazn

**Comment by firework8** [comment]
Thanks for your interest on our work. Below is the detailed explanation of N, M, T, V, and C.

N: number of training samples in the current batch (e.g. N=16)
M: number of people in the sample (e.g. M=2)
T: number of frames (e.g. T=100)
V: number of keypoints (e.g. V=25 for NTU RGB+D 3D skeleton)
C: number of dimensions for skeleton representions (e.g. the initial C=3 for 3D keypoint)

Hope this could help you understand.
